---
abstract: 'multiplexing SNMP query engine client using AnyEvent'
author:
  - 'Anton Berezin, C<< <tobez at tobez.org> >>'
  - 'Anton Berezin <tobez@tobez.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SNMP-QueryEngine-AnyEvent
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 0.01
